name: Generate Snake Game

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: SaravanaPerumal  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-snake.svg

      - name: Add generated SVG to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -f dist/github-contribution-snake.svg
          git commit -m "Add latest GitHub contribution snake"
          git push origin main

      - name: Update README
        run: |
          sed -i 's|<img src="dist/github-contribution-snake.svg" alt="Snake animation" />|![GitHub Snake](dist/github-contribution-snake.svg)|' README.md
          git add README.md
          git commit -m "Update README with latest snake"
          git push origin main
